---
title: "forcasting forest fires"
author: "fantastic fouR: Eli Levine, Hannah Long, Preetha Ramachandran"
date: "Oct. 26, 2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      warning = FALSE, 
                      message = FALSE)
```

Your written report goes here! Before you submit, make sure your code chunks are turned off with `echo = FALSE` and there are no warnings or messages with `warning = FALSE` and `message = FALSE` 

```{r load-packages}
library(tidyverse)
library(broom)
library(patchwork)
library(knitr)
```

```{r load-data}
fire <- readr::read_csv('data/all_conditions.csv')
```

###Introduction

We started by creating distribution plots for each of the continuous variables.



```{r}
fire <- fire %>%
  mutate(avgsoiltemp = `Avg Soil Temp (F)`,
         windrun = `Wind Run (miles)`,
         avgwindspeed = `Avg Wind Speed (mph)`,
         dewpoint = `Dew Point (F)`,
         avgrelhum = `Avg Rel Hum (%)`,
         minrelhum = `Min Rel Hum (%)`,
         maxrelhum = `Max Rel Hum (%)`,
         avgairtemp = `Avg Air Temp (F)`,
         minairtemp = `Min Air Temp (F)`)
```


```{r}
ggplot(data = fire, aes(x = Avg Soil Temp (F))) +
  geom_histogram(stat = "count") +
  labs(x = "Avg Soil Temp (F)",
       y = "Count",
       title = "Distribution of Avg Soil Temp (F)")
```

